- name: download neovim tarball
  become: yes
  become_user: root
  get_url:
    url:  https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    dest: /tmp/nvim-linux64.tar.gz
    mode: 0755


- name: extract neovim tarball
  become: yes
  become_user: root
  ansible.builtin.unarchive:
    src: /tmp/nvim-linux64.tar.gz
    dest: /opt
    remote_src: yes
    creates: /opt/nvim-linux64


