---

# import tasks

- import_tasks: install_cargo.yml
- import_tasks: install_bandwhich.yml



- name: package | bottom | install
  community.general.cargo:
    name: bottom
    state: latest
    locked: true