- name: installing core packages
  become: yes
  apt:
    name: 
      # build tools
      - build-essential
      - cmake
      - autoconf
      - automake
      - libtool
      - pkg-config
      # basic tools
      - git
      - curl
      - wget
      - unzip
      - zip
      - tar
      - jq
      # network tools
      - net-tools
      - iputils-ping
      - dnsutils
      # monitoring tools
      - htop
      - iotop
      - iftop
      - nload
      - ctop
      # command line tools
      - exa
    state: latest


# install rust/cargo
- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Install Rust/Cargo
  when: cargo_exists is failed
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  tags: rust


# install some packages using cargo
- name: Install bandwhich
  community.general.cargo:
    name: bandwhich
    locked: true

- name: Install bat
  community.general.cargo:
    name: bat
    locked: true

- name: Install bottom
  community.general.cargo:
    name: bottom
    locked: true

# import repos.yml
- import_tasks: repos.yml