---
- name: install common tools
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - curl
    - wget
    - unzip
    - htop
    - jq
    - tree
    - ruby
    - ruby-dev
    - rubygems
    - neofetch


- import_tasks: install_cargo.yml
- import_tasks: install_omz.yml
- import_tasks: install_fzf.yml
- import_tasks: install_neovim.yml




- name: install cargo packages
  community.general.cargo:
    name: "{{ item }}"
    state: latest
  loop:
    - bandwhich
    - bottom
    - ripgrep
    - fd-find
    - zoxide
    - starship
    - du-dust
    - tokei
    - bat

   

- name:  add capabilities to bandwhich
  become: yes
  shell: sudo setcap cap_sys_ptrace,cap_dac_read_search,cap_net_raw,cap_net_admin+ep $(command -v bandwhich)


- name: install gem packages
  become: yes
  command: sudo gem install {{ item }}
  loop:
    - colorls