---

- name: add some apt repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - ppa:bashtop-monitor/bashtop

- name: installing core packages
  become: true
  apt:
    name: 
      # build tools
      - build-essential
      - cmake
      - autoconf
      - automake
      - libtool
      - pkg-config
      # snapd
      - snapd
      # basic tools
      - git
      - curl
      - wget
      - unzip
      - zip
      - tar
      - jq
      - gh
      # network tools
      - net-tools
      - iputils-ping
      - dnsutils
      # monitoring tools
      - htop
      - iotop
      - iftop
      - nload
      - ctop
      - bashtop
      # command line tools
      - bat
      - exa
      - fd-find
      - fzf
      - fzy
      - ripgrep
      - tmux
      - zoxide
      - zsh
      - nnn
      - neofetch
      # languages tools
      - python3-dev
      - python3-pip
      - python3-venv
      - python3-setuptools
    state: latest

# installing pip packages
- name: installing pip packages
  become: true
  pip:
    name:
      - thefuck
    state: latest

- name: installing nvim
  become: true
  community.general.snap:
    name:
      - nvim
    classic: true

- name: installing starship
  become: true
  shell: curl -fsSL https://starship.rs/install.sh | sh -s -- -y
  args:
    creates: /usr/local/bin/starship



