#!/bin/bash

set -e


# SCRIPT_DIR is the directory of the script file
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "SCRIPT_DIR: $SCRIPT_DIR"


function have {
  command -v "$1" &>/dev/null
}

# install ansible

if ! have ansible; then
  if have apt-get; then
    sudo apt-get update
    sudo apt-get install -y software-properties-common
    sudo apt-add-repository -y ppa:ansible/ansible
    sudo apt-get update
    sudo apt-get install -y ansible
  elif have yum; then
    sudo yum install -y epel-release
    sudo yum install -y ansible
  else
    echo "No package manager found. You must install ansible manually."
    exit 1
  fi
fi

# Run Ansible
ansible-playbook -i $SCRIPT_DIR/hosts $SCRIPT_DIR/linux.yml --ask-become-pass