#!/bin/bash

set -e


# SCRIPT_DIR is the directory of the script file
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


function have {
  command -v "$1" &>/dev/null
}

# install python3 and pip3
if ! have python3; then
  sudo apt-get update
  sudo apt-get install -y python3
  sudo apt-get install -y python3-pip
  pip3 install --upgrade pip
fi

# install ansible using pip
if ! have ansible; then
  pip3 install ansible
fi
# install ansible dependencies
ansible-galaxy install -r $SCRIPT_DIR/requirements.yml



# Run Ansible
ansible-playbook -i $SCRIPT_DIR/hosts $SCRIPT_DIR/linux.yml --ask-become-pass