
- name: insure fc-cache is installed
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: fontconfig
    state: present

- name: Download Nerd Fonts
  include_tasks: download.yml
  loop:
    - FiraCode
    - DejaVuSansMono
    - JetBrainsMono
    - FantasqueSansMono
    - VictorMono
    - SourceCodePro
    - Hack