---
- name: Create ~/.config
  file:
    path: ~/.config
    state: directory

- name: Find .config files
  find:
    paths: ~/dlndot/config/
    recurse: no
    file_type: any
    hidden: yes
  register: dot_config

- name: ~/.config/
  file:
    src: "{{item.path}}"
    dest: "~/.config/{{item.path | basename}}"
    state: link
    force: yes
  loop: "{{ dot_config.files }}"
  loop_control:
    label: "~/.config/{{item.path | basename}}"

- name: .bashrc
  copy:
    dest: ~/.bashrc
    content: "{{ lookup('file', '~/dlndot/.bashrc') }}"


- name: nvim
  file:
    src: ~/dlndot/nvim
    dest: ~/.config/nvim
    state: link

  
- name: .gitconfig
  file:
    src: ~/.config/.gitconfig
    dest: ~/.gitconfig
    state: link

   